services:
  redis:
    image: redis:7-alpine
    container_name: hyperv-redis
    environment:
      TZ: Africa/Cairo
    volumes:
      - hyperv-redis-data:/data
    restart: unless-stopped
    networks:
      - hyperv-nw

  postgres:
    image: postgres:16-alpine
    container_name: hyperv-postgres
    environment:
      POSTGRES_DB: hyperv_inventory
      POSTGRES_USER: hyperv
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Africa/Cairo
    volumes:
      - hyperv-pg-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - hyperv-nw

  web:
    build: .
    container_name: hyperv-web
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Africa/Cairo
      SERVICE: web
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DATABASE_URL: postgresql://hyperv:${POSTGRES_PASSWORD}@postgres:5432/hyperv_inventory
      REDIS_URL: redis://redis:6379/0
    volumes:
      - hyperv-app-data:/opt/hyperv_inventory/data
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      hyperv-nw:
      reverseproxy-nw:
      hyperv-ipvlan:
        ipv4_address: 10.2.24.10
  celery-worker:
    build: .
    container_name: hyperv-celery-worker
    dns:
      - 10.2.201.100
      - 10.2.200.100
      - 8.8.8.8
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Africa/Cairo
      SERVICE: celery-worker
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgresql://hyperv:${POSTGRES_PASSWORD}@postgres:5432/hyperv_inventory
      REDIS_URL: redis://redis:6379/0
    volumes:
      - hyperv-app-data:/opt/hyperv_inventory/data
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      hyperv-nw:
      hyperv-ipvlan:
        ipv4_address: 10.2.24.11

  celery-beat:
    build: .
    container_name: hyperv-celery-beat
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Africa/Cairo
      SERVICE: celery-beat
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgresql://hyperv:${POSTGRES_PASSWORD}@postgres:5432/hyperv_inventory
      REDIS_URL: redis://redis:6379/0
    volumes:
      - hyperv-app-data:/opt/hyperv_inventory/data
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - hyperv-nw

volumes:
  hyperv-redis-data:
    driver: local
  hyperv-pg-data:
    driver: local
  hyperv-app-data:
    driver: local

networks:
  hyperv-nw:
    driver: bridge

  reverseproxy-nw:
    external: true

  hyperv-ipvlan:
    driver: ipvlan
    driver_opts:
      parent: eth2
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 10.2.24.0/24
          gateway: 10.2.24.1
          ip_range: 10.2.24.10/31
